### ISSUE TITLE
fullWidth prop is ignored for FormikSelect fields

### ISSUE THREAD

**Issue by AubreyF** [DCCS-IT-Business-Solutions/react-formik-mui#13]
@dccs/react-formik-mui V0.9.5.

Repro: https://codesandbox.io/s/react-formik-mui-testing-4pn0p?fontsize=14&hidenavigation=1&theme=dark

![image](https://user-images.githubusercontent.com/2789037/69305718-d1917100-0bd9-11ea-89a5-216d6b8953d3.png)

**Comment by mvitzthum** [comment]
https://material-ui.com/api/select/

Material-UI Selects don't have a fullWidth prop.

<FormikSelect> render  the following simplyfied structure (taken from https://material-ui.com/components/selects/)

<FormControl>
   <InputLabel />
   <Select> 
     <MenuItem/>
     <MenuItem/>
     <MenuItem/>
   </Select>
</FormControl>

To achieve fullWidth on Selects you have to do it like this:
![image](https://user-images.githubusercontent.com/47003029/69319714-020bf600-0c40-11ea-9e83-3714d25c6409.png)

formControlProps then get passed to <FormControl> like this:
![image](https://user-images.githubusercontent.com/47003029/69319769-210a8800-0c40-11ea-8169-2373eb75de6b.png)
