### ISSUE TITLE
FormikSwitch doesn't read or write value of property

### ISSUE THREAD

**Issue by fabianrieder** [DCCS-IT-Business-Solutions/react-formik-mui#16]
The FormikSwitch doesn't read or write the value  of the assigned property (defined with 'name').

Reproducible in the example provided in the description.
- Set the value of 'switch' from "" to true
--> The slider doesn't react to this change
- Set the value of 'switch' from true to false
--> also no change in the ui

Regards, Fabian

**Comment by mvitzthum** [comment]
fixed in 0.10.3
