### ISSUE TITLE
Validation throwing "Invalid prop `error` of type `string`" warnings

### ISSUE THREAD

**Issue by AubreyF** [DCCS-IT-Business-Solutions/react-formik-mui#18]
Validation is throwing console warnings in the latest version of react-formik-mui, formik, and @material-ui/core:
```
Warning: Failed prop type: Invalid prop `error` of type `string` supplied to `ForwardRef(FormControl)`, expected `boolean`.
    in ForwardRef(FormControl) (created by WithStyles(ForwardRef(FormControl)))
    in WithStyles(ForwardRef(FormControl)) (created by ForwardRef(TextField))
    in ForwardRef(TextField) (created by WithStyles(ForwardRef(TextField)))
    in WithStyles(ForwardRef(TextField)) (created by FastFieldInner)
    in FastFieldInner (created by Context.Consumer)
    in FormikConnect(FastFieldInner)
    in Unknown (created by FormikTextField)
    in FormikTextField (created by Formik)
   ...
```

Here's my [repro from last year](https://github.com/DCCS-IT-Business-Solutions/react-formik-mui/issues/11), which works fine now that the issue it originally surfaced has been fixed:
https://codesandbox.io/embed/react-formik-mui-testing-4pn0p

Here's a newer version, identical to the previous other than that I upgraded a few library versions to their latest:
https://codesandbox.io/s/react-formik-mui-testing-0twvn

As you can see, this newer version throws the following errors after empty fields are blurred and validation errors are surfaced:

![image](https://user-images.githubusercontent.com/2789037/80782946-f694f300-8b2c-11ea-8917-454c9104bef9.png)

**Comment by mvitzthum** [comment]
Fixed in Version v0.11.4
