### ISSUE TITLE
Strange display of current date

### ISSUE THREAD

**Issue by stephanmeissner** [DCCS-IT-Business-Solutions/react-formik-mui#3]
![image](https://user-images.githubusercontent.com/45164316/66062109-16d1e480-e541-11e9-8536-00063c7e08ea.png)

**Comment by mvitzthum** [comment]
Here is the documentation for momentjs
https://material-ui-pickers.dev/localization/moment

The examples in the storybook use datefns

**Comment by mvitzthum** [comment]
default dateformat is "dd.MM.yyyy".
This works for datefns, but not moment.

This will work for moment "DD.MM.YYYY"
