### ISSUE TITLE
Autocomplete: Missing display value after value selection

### ISSUE THREAD

**Issue by waretec** [DCCS-IT-Business-Solutions/react-formik-mui#5]
I use the Autocomplete control but after selecting any value it is not displayed in the UI. Against my expectactions the selected value IS binded correctly. Here a short code snippet:

```Javascript
<FormikAutocomplete
                label="Super Document"
                value={documentFormPayload.superDocument.value}
                name="superDocument"
                onLoadOptions={(query: String) => {
                  return documentFormPayload.superDocument.values;
                }}
                valueProp={o => o}
                textProp={o => o.id + ": " + o.name}
              />
```

**Comment by DCCSReschAndreas** [comment]
Hi,
i can't replicate your problem.
Seems like this is something specific to your application.
@waretec  You could try to replicate the problem in a codesandbox to share it with us.
