### ISSUE TITLE
Checkbox does not display initial value

### ISSUE THREAD

**Issue by waretec** [DCCS-IT-Business-Solutions/react-formik-mui#6]
The checkbox does not work when it comes to displaying initial true(=checked) values.

**Comment by mvitzthum** [comment]
Fixed in Version 0.7.2 :)

Here is an example for checkboxes (Radio + Switches fixed aswell)
https://dccs-it-business-solutions.github.io/react-formik-mui/?path=/story/formik--checkboxes
