### ISSUE TITLE
arning: Failed prop type: Invalid prop `checked` of type `array` supplied to `ForwardRef(Checkbox)`, expected `boolean`.

### ISSUE THREAD

**Issue by owlyowl** [DCCS-IT-Business-Solutions/react-formik-mui#8]
Checkboxes and radios are failing with:
warning: Failed prop type: Invalid prop `checked` of type `array` supplied to `ForwardRef(Checkbox)`, expected `boolean`.

versions:
formik": "^2.0.3",
    "@date-io/date-fns": "^1.3.11",
    "@dccs/react-filepicker-mui": "0.0.3",
    "@dccs/react-formik-mui": "^0.7.3",
    "@dccs/utils": "^0.2.2",
    "@material-ui/core": "^4.5.2",
    "@material-ui/icons": "^4.5.1",
    "@material-ui/pickers": "^3.2.7",

**Comment by mvitzthum** [comment]
Hey @owlyowl 
can you try to reproduce it in https://codesandbox.io/ or another online editor of your choice? :)

**Comment by owlyowl** [comment]
Sure I'll try and get something up tomorrow.

I just used your online example index.tsx markup and popped it in a
component with those particular versions of the npm packages.

**Comment by AubreyF** [comment]
@mvitzthum I just encountered this situation as well, and I created a repro for us:

https://codesandbox.io/s/formik-recaptcha-example-c1m3g?fontsize=14&hidenavigation=1&theme=dark

Please note that I am using the formik-material-ui library, and that @owlyowl is using the react-formik-mui lib. It appears that the way both of these libs handle checkboxes does not play nicely with the latest version of Formik.

**Comment by mvitzthum** [comment]
Thx! ill try to get it fixed.

**Comment by AubreyF** [comment]
> @AubreyF
> 
> Thx! ill try to get it fixed today.
> 
> Update 1:
> I tried to reproduce it with our @dccs/react-formik-mui package, but it works for me.
> It might have been fixed between version 0.7.3 and the current one
> 
> Here is your example with both formik-material-ui and react-formik-mui
> https://codesandbox.io/s/formik-recaptcha-example-5nesu
> 
> Update 2:
> Tried it with 0.7.3 in codesandbox. Works aswell :)

@mvitzthum Thanks for taking a look at this! Are you sure it's working for you? Check2 is broken for me in Chrome 78 in your provided 5nesu codesandbox example.

![image](https://user-images.githubusercontent.com/2789037/69170212-91819f80-0aae-11ea-84fc-14f00f3007b7.png)

**Comment by mvitzthum** [comment]
@AubreyF 
Hey, 
i should have explained myself better :D 

Checkbox "check1" is using our lib "react-formik-mui" -> works 
Checkbox "check2" is using the other lib "formik-matrerial-ui" -> doesn't work

**Comment by AubreyF** [comment]
Thanks @mvitzthum!

I just switched the project I am working on over to react-formik-mui, and your code is working as expected. 👍
