### ISSUE TITLE
FormikDatePicker throws Warning: Received `true` for a non-boolean attribute `clearable`. in Console

### ISSUE THREAD

**Issue by DCCSReschAndreas** [DCCS-IT-Business-Solutions/react-formik-mui#9]
`<FormikDatepicker name="start" fullWidth></FormikDatepicker>`
throws the following error:
![image](https://user-images.githubusercontent.com/54944804/68378053-bc353500-014b-11ea-8dd2-3625880836c5.png)

I am using the 
```json
"@dccs/react-formik-mui": "^0.9.0",
"@material-ui/pickers": "^3.2.7",
"@material-ui/core": "^4.5.1",
"@material-ui/icons": "^4.5.1",
"@material-ui/lab": "^4.0.0-alpha.29",
```

**Comment by mvitzthum** [comment]
Fixed in Version 0.9.3
